# fly.toml file generated for car-center on 2023-04-13T00:24:22+02:00

app = "car-center"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  [build.args]
    PHP_VERSION = "8.1"
    NODE_VERSION = "16.19.1"

[env]
  LOG_CHANNEL="stack"
  LOG_LEVEL="debug"

[experimental]
  auto_rollback = true

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.http_checks]]
    grace_period = "2s"
    interval = 5000
    method = "get"
    path = "/"
    protocol = "http"
    restart_limit = 5
    timeout = 2000
    tls_skip_verify = true

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
